name: 'ğŸ”— Check Broken Links'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

permissions:
  contents: read

jobs:
  check-links:
    if: github.repository_owner == 'langchain-ai' || github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: 'ğŸŸ¢ Setup Node.js 18.x'
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: ./docs/yarn.lock
      - name: 'ğŸ“¦ Install Node Dependencies'
        run: yarn install --immutable --mode=skip-build
        working-directory: ./docs
      - name: 'ğŸ” Scan Documentation for Broken Links'
        run: yarn check-broken-links
        working-directory: ./docs
